export const Data = [
  {
    postId: 9,
    id: 41,
    name: "voluptas deleniti ut",
    email: "Lucio@gladys.tv",
    body: "facere repudiandae vitae ea aut sed quo ut et\nfacere nihil ut voluptates in\nsaepe cupiditate accusantium numquam dolores\ninventore sint mollitia provident",
  },
  {
    postId: 9,
    id: 42,
    name: "nam qui et",
    email: "Shemar@ewell.name",
    body: "aut culpa quaerat veritatis eos debitis\naut repellat eius explicabo et\nofficiis quo sint at magni ratione et iure\nincidunt quo sequi quia dolorum beatae qui",
  },
  {
    postId: 9,
    id: 43,
    name: "molestias sint est voluptatem modi",
    email: "Jackeline@eva.tv",
    body: "voluptatem ut possimus laborum quae ut commodi delectus\nin et consequatur\nin voluptas beatae molestiae\nest rerum laborum et et velit sint ipsum dolorem",
  },
  {
    postId: 9,
    id: 44,
    name: "hic molestiae et fuga ea maxime quod",
    email: "Marianna_Wilkinson@rupert.io",
    body: "qui sunt commodi\nsint vel optio vitae quis qui non distinctio\nid quasi modi dicta\neos nihil sit inventore est numquam officiis",
  },
  {
    postId: 9,
    id: 45,
    name: "autem illo facilis",
    email: "Marcia@name.biz",
    body: "ipsum odio harum voluptatem sunt cumque et dolores\nnihil laboriosam neque commodi qui est\nquos numquam voluptatum\ncorporis quo in vitae similique cumque tempore",
  },
  {
    postId: 10,
    id: 46,
    name: "dignissimos et deleniti voluptate et quod",
    email: "Jeremy.Harann@waino.me",
    body: "exercitationem et id quae cum omnis\nvoluptatibus accusantium et quidem\nut ipsam sint\ndoloremque illo ex atque necessitatibus sed",
  },
  {
    postId: 10,
    id: 47,
    name: "rerum commodi est non dolor nesciunt ut",
    email: "Pearlie.Kling@sandy.com",
    body: "occaecati laudantium ratione non cumque\nearum quod non enim soluta nisi velit similique voluptatibus\nesse laudantium consequatur voluptatem rem eaque voluptatem aut ut\net sit quam",
  },
];
